---
driver:
  name: digitalocean
driver_config:
  ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6-5-x64
  - name: ubuntu-12-04-x64
  - name: debian-7-0-x64

suites:
  - name: default
    run_list:
      - recipe[opt-python::default]
    attributes: {}
  - name: modulefile
    run_list:
      - recipe[environment-modules::default]
      - recipe[opt-python::default]
    attributes: { opt-python: {gen_modulefile: true } }
  - name: setuptools
    run_list:
      - recipe[opt-python::default]
    attributes: { opt-python: { include_recipes: [_setuptools] } }
  - name: pip
    run_list:
      - recipe[opt-python::default]
    attributes: { opt-python: { include_recipes: [_pip] } }
  - name: cython
    run_list:
      - recipe[opt-python::default]
    attributes: { opt-python: { include_recipes: [_cython] } }
  - name: numpy
    run_list:
      - recipe[opt-python::default]
    attributes: { opt-python: { include_recipes: [_numpy] } }
