---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
      customize:
        memory: 512
        cpuexecutioncap: 50

suites:
  - name: default
    run_list:
      - recipe[python::default]
    attributes: {}
  - name: modulefile
    run_list:
      - recipe[environment-modules::default]
    attributes: {}
