---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
      customize:
        memory: 768
        cpuexecutioncap: 50

suites:
  - name: default
    run_list:
      - recipe[python::default]
    attributes: {}
  - name: python3
    run_list:
      - recipe[python::default]
    attributes: {
      "python": {
        "version": "3.4.1"
      }
    }
  - name: with-module
    run_list:
      - recipe[python::default]
      - recipe[environment-modules::default]
      - recipe[python::modulefile]
    attributes: {}
